// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwmOVQ1bjGPD9UCwtm3W5Ed0uXr3iRsoc',
    appId: '1:873494706483:web:a2b1397505d5575c416646',
    messagingSenderId: '873494706483',
    projectId: 'javi-website',
    authDomain: 'javi-website.firebaseapp.com',
    storageBucket: 'javi-website.firebasestorage.app',
    measurementId: 'G-L5RS3JDTZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqmVrbYi9lu2Q2iMep6OtLU4xgpFGZso',
    appId: '1:873494706483:android:c20ad84b24915ea4416646',
    messagingSenderId: '873494706483',
    projectId: 'javi-website',
    storageBucket: 'javi-website.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHrYsHhX1YGLVExDw1vJrKvfIeRVKTDc',
    appId: '1:873494706483:ios:2776b342cca4d150416646',
    messagingSenderId: '873494706483',
    projectId: 'javi-website',
    storageBucket: 'javi-website.firebasestorage.app',
    iosBundleId: 'com.example.javierWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHrYsHhX1YGLVExDw1vJrKvfIeRVKTDc',
    appId: '1:873494706483:ios:2776b342cca4d150416646',
    messagingSenderId: '873494706483',
    projectId: 'javi-website',
    storageBucket: 'javi-website.firebasestorage.app',
    iosBundleId: 'com.example.javierWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwmOVQ1bjGPD9UCwtm3W5Ed0uXr3iRsoc',
    appId: '1:873494706483:web:9809bcbca2f572d5416646',
    messagingSenderId: '873494706483',
    projectId: 'javi-website',
    authDomain: 'javi-website.firebaseapp.com',
    storageBucket: 'javi-website.firebasestorage.app',
    measurementId: 'G-TTXN9RYN2X',
  );

}